"""
JEEVidya — Caption Engine
Parses VTT files generated by edge-tts and creates MoviePy TextClips.
Implements karaoke-style highlighting for retention optimization.
"""
import re
from typing import List, Dict, Any

from config import settings, brand


def parse_vtt(vtt_path: str) -> List[Dict[str, Any]]:
    """Parse a VTT file and return a list of caption timing dictionaries."""
    captions = []
    
    if not vtt_path:
        return captions
        
    try:
        with open(vtt_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            
        current_caption = None
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('WEBVTT'):
                continue
                
            # Match timing line: 00:00:00.000 --> 00:00:01.000
            timing_match = re.match(r'(\d{2}:\d{2}:\d{2}\.\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})', line)
            if timing_match:
                start_time = _time_to_seconds(timing_match.group(1))
                end_time = _time_to_seconds(timing_match.group(2))
                current_caption = {"start": start_time, "end": end_time, "text": ""}
            elif current_caption:
                # Add text to current caption (handling multiple lines)
                if current_caption["text"]:
                    current_caption["text"] += " " + line
                else:
                    current_caption["text"] = line
                    captions.append(current_caption)
                    # We create a new dict on the next timing match, so we don't reset here
                    
    except Exception as e:
        print(f"Warning: Failed to parse VTT {vtt_path}: {e}")
        
    # Group words into larger chunks for better readability (Shorts style: 2-3 words per line)
    return _chunk_captions(captions)


def _time_to_seconds(time_str: str) -> float:
    """Convert VTT time format (HH:MM:SS.mmm) to seconds."""
    h, m, s = time_str.split(':')
    s, ms = s.split('.')
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000.0


def _chunk_captions(word_captions: List[Dict[str, Any]], max_chars: int = settings.CAPTION_MAX_CHARS_PER_LINE) -> List[Dict[str, Any]]:
    """Group word-level timings into phrase-level timings."""
    if not word_captions:
        return []
        
    chunks = []
    current_chunk = None
    
    for cap in word_captions:
        if not current_chunk:
            current_chunk = {"start": cap["start"], "end": cap["end"], "text": cap["text"]}
        elif len(current_chunk["text"]) + len(cap["text"]) + 1 <= max_chars:
            current_chunk["text"] += " " + cap["text"]
            current_chunk["end"] = cap["end"]
        else:
            chunks.append(current_chunk)
            current_chunk = {"start": cap["start"], "end": cap["end"], "text": cap["text"]}
            
    if current_chunk:
        chunks.append(current_chunk)
        
    return chunks


def build_caption_clips(captions: List[Dict[str, Any]], width: int, height: int):
    """
    Build MoviePy clips for captions.
    Note: Returns a list of MoviePy elements.
    Requires MoviePy to be installed (handled in compositor).
    """
    from moviepy.editor import TextClip, CompositeVideoClip
    
    clips = []
    
    y_pos = int(height * settings.CAPTION_Y_POSITION)
    
    for cap in captions:
        duration = cap["end"] - cap["start"]
        if duration <= 0:
            continue
            
        # Background shadow for readability
        shadow = TextClip(
            cap["text"],
            fontsize=settings.CAPTION_FONT_SIZE,
            color='black',
            font='Arial-Bold', # Fallback safe font for MoviePy
            method='caption',
            size=(width - 100, None),
            align='center'
        )
        shadow = shadow.set_position(('center', y_pos + 4)).set_start(cap["start"]).set_duration(duration)
        
        # Main text
        txt_clip = TextClip(
            cap["text"],
            fontsize=settings.CAPTION_FONT_SIZE,
            color='white',
            stroke_color='black',
            stroke_width=2,
            font='Arial-Bold',
            method='caption',
            size=(width - 100, None),
            align='center'
        )
        txt_clip = txt_clip.set_position(('center', y_pos)).set_start(cap["start"]).set_duration(duration)
        
        clips.extend([shadow, txt_clip])
        
    return clips
